# Generated by Django 3.1.2 on 2020-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=6)),
                ('to_currency', models.CharField(max_length=6)),
                ('exchange_rate_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
