# Generated by Django 3.1.2 on 2020-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=19),
        ),
    ]
