# Generated by Django 3.1.2 on 2020-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerates', '0002_rate_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='exchange_rate_date',
            field=models.DateField(),
        ),
    ]
